import { ITeam } from "components/TiersList/interface";

export const ALL_TEAMS: ITeam[] = [
  {
    id: 1,
    tier: 1,
    tokenType: '1',
    name: 'Brazil',
    flag: 'public/images/teams/vertical/1.png',
    fifaCode: 'BRA',
    group: 'G',
    rarity: '0.08',
  },
  {
    id: 2,
    tier: 1,
    tokenType: '2',
    name: 'France',
    flag: 'public/images/teams/vertical/2.png',
    fifaCode: 'FRA',
    group: 'D',
    rarity: '0.1',
  },
  {
    id: 3,
    tier: 1,
    tokenType: '3',
    name: 'England',
    flag: 'public/images/teams/vertical/3.png',
    fifaCode: 'ENG',
    group: 'B',
    rarity: '0.11',
  },
  {
    id: 4,
    tier: 1,
    tokenType: '4',
    name: 'Spain',
    flag: 'public/images/teams/vertical/4.png',
    fifaCode: 'ESP',
    group: 'E',
    rarity: '0.14',
  },
  {
    id: 5,
    tier: 1,
    tokenType: '5',
    name: 'Germany',
    flag: 'public/images/teams/vertical/5.png',
    fifaCode: 'GER',
    group: 'E',
    rarity: '0.19',
  },
  {
    id: 6,
    tier: 1,
    tokenType: '6',
    name: 'Argentina',
    flag: 'public/images/teams/vertical/6.png',
    fifaCode: 'ARG',
    group: 'C',
    rarity: '0.19',
  },
  {
    id: 7,
    tier: 1,
    tokenType: '7',
    name: 'Belgium',
    flag: 'public/images/teams/vertical/7.png',
    fifaCode: 'BEL',
    group: 'F',
    rarity: '0.22',
  },
  {
    id: 8,
    tier: 1,
    tokenType: '8',
    name: 'Portugal',
    flag: 'public/images/teams/vertical/8.png',
    fifaCode: 'POR',
    group: 'H',
    rarity: '0.22',
  },
  {
    id: 9,
    tier: 2,
    tokenType: '9',
    name: 'Nederland',
    flag: 'public/images/teams/vertical/9.png',
    fifaCode: 'NL',
    group: 'A',
    rarity: '0.26',
  },
  {
    id: 10,
    tier: 2,
    tokenType: '10',
    name: 'Denmark',
    flag: 'public/images/teams/vertical/10.png',
    fifaCode: 'DEN',
    group: 'D',
    rarity: '0.52',
  },
  {
    id: 11,
    tier: 2,
    tokenType: '11',
    name: 'Croatia',
    flag: 'public/images/teams/vertical/11.png',
    fifaCode: 'CRO',
    group: 'F',
    rarity: '0.65',
  },
  {
    id: 12,
    tier: 2,
    tokenType: '12',
    name: 'Uruguay',
    flag: 'public/images/teams/vertical/12.png',
    fifaCode: 'URU',
    group: 'H',
    rarity: '0.93',
  },
  {
    id: 13,
    tier: 2,
    tokenType: '13',
    name: 'Poland',
    flag: 'public/images/teams/vertical/13.png',
    fifaCode: 'POL',
    group: 'C',
    rarity: '1.21',
  },
  {
    id: 14,
    tier: 2,
    tokenType: '14',
    name: 'Senegal',
    flag: 'public/images/teams/vertical/14.png',
    fifaCode: 'SN',
    group: 'A',
    rarity: '1.21',
  },
  {
    id: 15,
    tier: 2,
    tokenType: '15',
    name: 'America',
    flag: 'public/images/teams/vertical/15.png',
    fifaCode: 'USA',
    group: 'B',
    rarity: '1.49',
  },
  {
    id: 16,
    tier: 2,
    tokenType: '16',
    name: 'Serbia',
    flag: 'public/images/teams/vertical/16.png',
    fifaCode: 'SRB',
    group: 'G',
    rarity: '1.49',
  },
  {
    id: 17,
    tier: 3,
    tokenType: '17',
    name: 'Switzerland',
    flag: 'public/images/teams/vertical/17.png',
    fifaCode: 'SUI',
    group: 'G',
    rarity: '1.49',
  },
  {
    id: 18,
    tier: 3,
    tokenType: '18',
    name: 'Mexico',
    flag: 'public/images/teams/vertical/18.png',
    fifaCode: 'MEX',
    group: 'C',
    rarity: '1.86',
  },
  {
    id: 19,
    tier: 3,
    tokenType: '19',
    name: 'Wales',
    flag: 'public/images/teams/vertical/19.png',
    fifaCode: 'WAL',
    group: 'B',
    rarity: '1.86',
  },
  {
    id: 20,
    tier: 3,
    tokenType: '20',
    name: 'Ghana',
    flag: 'public/images/teams/vertical/20.png',
    fifaCode: 'GHA',
    group: 'H',
    rarity: '2.8',
  },
  {
    id: 21,
    tier: 3,
    tokenType: '21',
    name: 'Ecuador',
    flag: 'public/images/teams/vertical/21.png',
    fifaCode: 'ECU',
    group: 'A',
    rarity: '2.8',
  },
  {
    id: 22,
    tier: 3,
    tokenType: '22',
    name: 'Morocco',
    flag: 'public/images/teams/vertical/22.png',
    fifaCode: 'MAR',
    group: 'F',
    rarity: '3.73',
  },
  {
    id: 23,
    tier: 3,
    tokenType: '23',
    name: 'Cameroon',
    flag: 'public/images/teams/vertical/23.png',
    fifaCode: 'CMR',
    group: 'G',
    rarity: '4.66',
  },
  {
    id: 24,
    tier: 3,
    tokenType: '24',
    name: 'Canada',
    flag: 'public/images/teams/vertical/24.png',
    fifaCode: 'CAN',
    group: 'F',
    rarity: '4.66',
  },
  {
    id: 25,
    tier: 4,
    tokenType: '25',
    name: 'Japan',
    flag: 'public/images/teams/vertical/25.png',
    fifaCode: 'JPN',
    group: 'E',
    rarity: '4.66',
  },
  {
    id: 26,
    tier: 4,
    tokenType: '26',
    name: 'Qatar',
    flag: 'public/images/teams/vertical/26.png',
    fifaCode: 'QAT',
    group: 'A',
    rarity: '4.66',
  },
  {
    id: 27,
    tier: 4,
    tokenType: '27',
    name: 'Tunisia',
    flag: 'public/images/teams/vertical/27.png',
    fifaCode: 'TUN',
    group: 'D',
    rarity: '5.59',
  },
  {
    id: 28,
    tier: 4,
    tokenType: '28',
    name: 'South Korea',
    flag: 'public/images/teams/vertical/28.png',
    fifaCode: 'KOR',
    group: 'H',
    rarity: '7.46',
  },
  {
    id: 29,
    tier: 4,
    tokenType: '29',
    name: 'Australia',
    flag: 'public/images/teams/vertical/29.png',
    fifaCode: 'AUS',
    group: 'D',
    rarity: '7.46',
  },
  {
    id: 30,
    tier: 4,
    tokenType: '30',
    name: 'Iran',
    flag: 'public/images/teams/vertical/30.png',
    fifaCode: 'IRN',
    group: 'B',
    rarity: '9.32',
  },
  {
    id: 31,
    tier: 4,
    tokenType: '31',
    name: 'Saudi Arabia',
    flag: 'public/images/teams/vertical/31.png',
    fifaCode: 'KSA',
    group: 'C',
    rarity: '9.32',
  },
  {
    id: 32,
    tier: 4,
    tokenType: '32',
    name: 'Costa Rica',
    flag: 'public/images/teams/vertical/32.png',
    fifaCode: 'CRC',
    group: 'E',
    rarity: '18.64',
  },
];
